### ISSUE TITLE
Misleading node name in the "Updated lending limits" log message

### ISSUE THREAD

**Issue by tardieu** [project-codeflare/appwrapper#253]
The "Updated lending limits" log message is emitted upon successful etcd update of the slack queue. If this update fails due to an update conflict, we repeat the update when reconciling the next queued node event which is often about another node. As a result, the node name embedded in the "updated lending limits" message is misleading suggesting the limit was updated because of the specific node whereas there is no such relationship.

We need to log the cause of lending limit changes in a way that identifies the responsible node. The "Updated node health information" log message only accounts for autopilot label changes.

**Comment by tardieu** [comment]
We should also include before and after lending limit values (or deltas) in these messages as opposed to only the final state.

**Comment by dgrove-oss** [comment]
The primary logging issues about misleading nodes were fixed as part of #255.

**Comment by dgrove-oss** [comment]
#256 logs the delta on changes.
