### ISSUE TITLE
Automatically infer PodSets for well-known kinds

### ISSUE THREAD

**Issue by dgrove-oss** [project-codeflare/appwrapper#65]
We can make the specification of a PodSet for Component optional for common cases when we can recognize the GVK of the component.  This would lower the barrier to entry for using AppWrappers.

Some low hanging fruit with PodSpecTemplates: Jobs, Deployments, StatefulSets, PyTorchJob, RayJobs/Clusters, JobSets.

We probably should do this in conjunction with an extension to the validating web hook that rejects an AppWrapper that contains any unknown GVKs that don't have explicit PodSets and appear to contain PodSpecTemplates within them.   A stricter alternative would be to also recognize common GVKs that don't create pods (Secrets, ConfigMaps, ServiceAccount, etc) and reject any unknown GVK that doesn't have an explicit PodSet (which may say `0` replicas for resources that don't create Pods).

**Comment by tardieu** [comment]
The initial implementation was merged in #108. Keeping this issue open for now until we decide whether to support a mode where unknowns GVKs are rejected.

**Comment by dgrove-oss** [comment]
Going to close this and open a new issue for the strict mode.
