### ISSUE TITLE
Allow PodSets to specify a replicaPath

### ISSUE THREAD

**Issue by dgrove-oss** [project-codeflare/appwrapper#97]
Motivation: eliminate user errors where the duplicated replica count gets out of synch.   All the CRDs of interest to us have a replica count in their Template somewhere "adjacent" to their PodSpecTemplate that we can refer to in the PodSet.

This will be a non-backwards compatible change in the AppWrapper CRD.

**Comment by dgrove-oss** [comment]
We should probably do this in conjunction with adding a structure to the Status that keeps the name, GVK, and replica count of the created resource to avoid needing to constantly parse the string to an integer and handle errors.  Parse it once when we are creating the resource and cache the information in the status.

**Comment by dgrove-oss** [comment]
During initial prototyping, discovered the obvious in retrospect complication that not every Kind of interest actually has an explicit replica count as an integer.   Decided instead to add `replicaPath` as an optional alternative and use webhooks both to validate that `replica` and `replicaPath` are consistent if both are explicitly provided and to expand `replicaPath` into the easier to handle internally `replica` so we only have to do the path parsing once during AppWrapper creation.

**Comment by tardieu** [comment]
Now that the `replica` count is inferred for common GVKs (#108), `replicaPath` is adding complexity without providing much value in return, so we decided to drop the field from the CRD (#109). 

#109
